import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

ThemeData ligthThemeData = ThemeData(
    useMaterial3: true,
    colorScheme: lightColorScheme,
    textTheme: TextTheme(
        bodyLarge: GoogleFonts.lato(color: Colors.black),
        displaySmall: GoogleFonts.lato(color: Colors.black),
        titleLarge: GoogleFonts.lato(color: Colors.black),
        headlineLarge: GoogleFonts.lato(color: Colors.black),
        headlineMedium: GoogleFonts.lato(color: Colors.black),
        headlineSmall: GoogleFonts.lato(color: Colors.black),
        displayMedium: GoogleFonts.lato(color: Colors.black)));
ThemeData darktThemeData = ThemeData(
    useMaterial3: true,
    colorScheme: darkColorScheme,
    textTheme: TextTheme(
        bodyLarge: GoogleFonts.lato(color: Colors.white),
        displaySmall: GoogleFonts.lato(color: Colors.white),
        titleLarge: GoogleFonts.lato(color: Colors.white),
        headlineLarge: GoogleFonts.lato(color: Colors.white),
        headlineMedium: GoogleFonts.lato(color: Colors.white),
        headlineSmall: GoogleFonts.lato(color: Colors.white),
        displayMedium: GoogleFonts.lato(color: Colors.white)));

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF275EA7),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFD6E3FF),
  onPrimaryContainer: Color(0xFF001B3D),
  secondary: Color(0xFF555F71),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFD9E3F9),
  onSecondaryContainer: Color(0xFF121C2B),
  tertiary: Color(0xFF6F5675),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFF9D8FE),
  onTertiaryContainer: Color(0xFF28132F),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  outline: Color(0xFF74777F),
  background: Color(0xFFFDFBFF),
  onBackground: Color(0xFF1A1B1E),
  surface: Color(0xFFFAF9FD),
  onSurface: Color(0xFF1A1B1E),
  surfaceVariant: Color(0xFFE0E2EC),
  onSurfaceVariant: Color(0xFF43474E),
  inverseSurface: Color(0xFF2F3033),
  onInverseSurface: Color(0xFFF1F0F4),
  inversePrimary: Color(0xFFA9C7FF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF275EA7),
  outlineVariant: Color(0xFFC4C6CF),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFA9C7FF),
  onPrimary: Color(0xFF003063),
  primaryContainer: Color(0xFF00468B),
  onPrimaryContainer: Color(0xFFD6E3FF),
  secondary: Color(0xFFBDC7DC),
  onSecondary: Color(0xFF273141),
  secondaryContainer: Color(0xFF3E4758),
  onSecondaryContainer: Color(0xFFD9E3F9),
  tertiary: Color(0xFFDCBCE1),
  onTertiary: Color(0xFF3E2845),
  tertiaryContainer: Color(0xFF563E5C),
  onTertiaryContainer: Color(0xFFF9D8FE),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  outline: Color(0xFF8E9099),
  background: Color(0xFF1A1B1E),
  onBackground: Color(0xFFE3E2E6),
  surface: Color(0xFF121316),
  onSurface: Color(0xFFC7C6CA),
  surfaceVariant: Color(0xFF43474E),
  onSurfaceVariant: Color(0xFFC4C6CF),
  inverseSurface: Color(0xFFE3E2E6),
  onInverseSurface: Color(0xFF1A1B1E),
  inversePrimary: Color(0xFF275EA7),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFFA9C7FF),
  outlineVariant: Color(0xFF43474E),
  scrim: Color(0xFF000000),
);
